### ISSUE TITLE
README can be removed from docs

### ISSUE THREAD

**Issue by yhcharles** [sql-machine-learning/sql-machine-learning.github.io#18]
This page is not necessary and can be removed from docs:
https://sql-machine-learning.github.io/docs/README.html

**Comment by tonyyang-svail** [comment]
+1

**Comment by wangkuiyi** [comment]
I agree that this README.md file is unnecessary.  I doubt that its existence is the casualty of the existence of the unnecessary link on our home page, as shown below:

<img width="1270" alt="Screen Shot 2019-04-19 at 2 07 25 PM" src="https://user-images.githubusercontent.com/1548775/56444259-d2ad9900-62ac-11e9-9e56-bfe668a41eca.png">
