### ISSUE TITLE
Should we remove /carousel.css

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sql-machine-learning.github.io#33]
I see that we have the file [/carousel.css](https://github.com/sql-machine-learning/sql-machine-learning.github.io/blob/master/carousel.css) and `/dist/carousel.css`, which seem duplicated. 

I don't remember when did we introduce these files; I don't see an explanation in our [wiki page](https://github.com/sql-machine-learning/sql-machine-learning.github.io/wiki/Site-Instructions) either. So, I am just wondering do we still need them? If not, how about we remove them?

**Comment by mxz96102** [comment]
All dist and carousel.css are from the version before I came, I'm not sure if it's necessary, so I keep it. If it's not needed, we can delete them

**Comment by wangkuiyi** [comment]
Thanks @mxz96102 . I will try remove it today. If everything runs well on locally, I will file a PR.
