### ISSUE TITLE
Should we rename _layouts/index.md into _layouts/page.md

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sql-machine-learning.github.io#34]
According to the Jekyll directory structure [explanation](https://jekyllrb.com/docs/structure/):

> _layouts -- These are the templates that wrap posts. Layouts are chosen on a post-by-post basis in the front matter, which is described in the next section. The liquid tag {{ content }} is used to inject content into the web page.

In our Wiki

> There are two kinds of page in this project now, Doc and Page

It seems that the two files currently in our `/_layouts` are `index.md` and `page.md` -- one for Doc and one for Page, and `index.md` is for the Page?

**Comment by mxz96102** [comment]
Now we don't have the single page, index is a special page, its layout need to be standalone. So we need to keep /_layout/index.html
