### ISSUE TITLE
Replace /gohive by a git-submodule to the gohive repo

### ISSUE THREAD

**Issue by wangkuiyi** [sql-machine-learning/sql-machine-learning.github.io#37]
I fired https://github.com/sql-machine-learning/gohive/pull/30 as the first step. After it gets merged, I will fire a PR in this repo to replace the subdirectory /gohive by a git-submodule pointing to https://github.com/sql-machine-learning/gohive.

**Comment by mxz96102** [comment]
If it's needed, I will do this after pr #41 merges

**Comment by weiguoz** [comment]
> If it's needed, I will do this after pr #41 merges

Go ahead, buddy! It's needed.
