### ISSUE TITLE
Unexpected documentation layout

### ISSUE THREAD

**Issue by tonyyang-svail** [sql-machine-learning/sql-machine-learning.github.io#91]
The following section appears at the left bar
```
Highly Available SQLFlow Server
Support Arbitrary Select Statements
Design Doc: Model Definition and Model Zoo
XGBoost Parameter Document
```

![Screen Shot 2019-10-22 at 10 53 28 AM](https://user-images.githubusercontent.com/29932814/67314989-8260ff00-f4ba-11e9-9e18-9bc8c0c843ad.png)

I believe it is introduced at #89. So I am reverting this commit.

**Comment by tonyyang-svail** [comment]
I feel the Homepage update should be less frequent since there is not a CI on the documentation structure.

I am not an expert on this topic. @terrytangyuan @weiguoz What do you think?

**Comment by terrytangyuan** [comment]
@tonyyang-svail In addition, the table of contents in https://sql-machine-learning.github.io/doc_index/elasticdl/ is blank. I think #90 will fix it.

**Comment by tonyyang-svail** [comment]
@terrytangyuan Thanks for the prompt fix. We need to figure out a systematic way to solve this issue.

I can think of two solutions.
1. Reduce the update frequency on our Homepage. The updates only occur before major events like major releases, conferences. During the update, the sql-machine-learning team checks all the pages manually.
1. Build up a CI that will ensure the document structure and links. I am not sure how feasible it is, though I do use [a script](https://github.com/sql-machine-learning/sqlflow/tree/develop/scripts/markdown_link_check) to check the links in sqlflow repo.

What do you guys think?

Notify @Yancey1989 @typhoonzero @llxxxll @shendiaomo @weiguoz.

**Comment by terrytangyuan** [comment]
@tonyyang-svail +1 to reduce update frequency. There are tools like [Selenium](https://www.browserstack.com/guide/python-selenium-to-run-web-automation-test) that can be used to automate the UI testing but not sure how useful/necessary this needs to be.
